name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Validate code style
        run: npm run lint
      - name: Run unit tests
        run: CI=true npm test -- --coverage --verbose
      - name: Build static assets
        run: npm run build
